### ISSUE TITLE
icons appears to be non-mono

### ISSUE THREAD

**Issue by chanw9** [laishulu/Sarasa-Mono-SC-Nerd#1]
The slanted prompt in `p10k` could not be shown correctly either [with or without padding](https://github.com/romkatv/powerlevel10k/blob/6dfd92f8c1d60892ea9b2a57e93cd22a8cb75c2a/config/p10k-lean-8colors.zsh#L106)
![image](https://user-images.githubusercontent.com/22463256/88389522-ffc6f080-cdf9-11ea-9bfa-b165c9c67c83.png)
with padding:
![image](https://user-images.githubusercontent.com/22463256/88389727-5d5b3d00-cdfa-11ea-95b0-dc6a4a574cfe.png)
without padding:
![image](https://user-images.githubusercontent.com/22463256/88389777-782db180-cdfa-11ea-92e3-99da0f5054da.png)

**Comment by laishulu** [comment]
正确的应该是 with padding:
完了应该是高度对齐方面有问题。
我记得p10k在配置的时候
有关于对齐这一块的。

如果不行的话，那我也解决不了。

**Comment by chanw9** [comment]
这个nerd font patcher的字符大小和更纱的大小不一样？字体的em size是1000，可是nerd font符号的em size是1248。

**Comment by laishulu** [comment]
从哪里看patch之后的em的呢？
我是小白，不懂啊~~~

代码里面是有em设定的。
https://github.com/ryanoasis/nerd-fonts/blob/5f748cdb104a241ec8ac229f24518f3f867e8eb2/font-patcher#L91

**Comment by chanw9** [comment]
Orz我也是小白，我在FontMerge里直接查看那些符号的。比如这个三角`E0BA`，这里单独把那几个点调整到1000，在p10k里显示就正常了
![image](https://user-images.githubusercontent.com/22463256/88450746-97791d00-ce94-11ea-8342-659ff5e7f51d.png)

**Comment by laishulu** [comment]
https://github.com/ryanoasis/nerd-fonts/blob/5f748cdb104a241ec8ac229f24518f3f867e8eb2/font-patcher#L597

icon和字体的长宽比不一样，patch 中保持了长宽比，为避免横向或者竖向挤在一起，就产生了这情况。
我可以试试不保持长宽比，这样，稍微有一点变形，但是比较均一。

**Comment by laishulu** [comment]
@chanw9 

新版发布，纵横双向scale，你去试用一下？

**Comment by laishulu** [comment]
我自己试了下，完美~~~
<img width="269" alt="Snipaste_2020-07-26_01-43-30" src="https://user-images.githubusercontent.com/1224321/88462894-725ecb80-cee1-11ea-890a-51df50d9541f.png">

**Comment by chanw9** [comment]
❤️很舒服
