### ISSUE TITLE
manjaro linux 从命令行中无法安装

### ISSUE THREAD

**Issue by ScriptGo** [laishulu/Sarasa-Mono-SC-Nerd#14]
manjaro linux 从命令行中无法安装, 但是从软件管理器中可以安装
![2022-02-13-142140_800x600_scrot](https://user-images.githubusercontent.com/847131/153741478-0e0c71d4-0bfb-4507-82b1-fd99c97b7970.png)

**Comment by DHWIDSA** [comment]
这似乎是由于网络原因无法访问AUR导致的，可以考虑使用paru替代yay或者为yay配置tuna镜像

可以尝试在终端输入

```sh
yay --aururl "https://aur.archlinux.org" --save
```

这应该是最简单的解决方案。
