### ISSUE TITLE
oh my posh只有少数图标能正常显示

### ISSUE THREAD

**Issue by XiaofengdiZhu** [laishulu/Sarasa-Mono-SC-Nerd#15]
如图，还需要做什么设置吗？
![Snipaste_2022-05-05_20-58-27](https://user-images.githubusercontent.com/16849698/166927967-7c73f3ec-2ac8-48d8-9884-667d04d9eaab.jpg)
![Snipaste_2022-05-05_20-57-40](https://user-images.githubusercontent.com/16849698/166927977-94ea7160-3c90-43e4-9460-4681e5602a1e.jpg)

**Comment by laishulu** [comment]
可能用的图标不含在字体之内。
这个没有办法。

**Comment by XiaofengdiZhu** [comment]
> 可能用的图标不含在字体之内。 这个没有办法。

从nerd官网下的其他nerd字体可以正常显示啊

**Comment by laishulu** [comment]
https://github.com/laishulu/Sarasa-Mono-SC-Nerd/blob/056fafb30636a01dc64e4b2a24800fab18878910/README.md?plain=1#L33

**Comment by XiaofengdiZhu** [comment]
> https://github.com/laishulu/Sarasa-Mono-SC-Nerd/blob/056fafb30636a01dc64e4b2a24800fab18878910/README.md?plain=1#L33

尴尬……
