### ISSUE TITLE
请问 emacs 里怎么设置字体大小和字重了？

### ISSUE THREAD

**Issue by yufengwang** [laishulu/Sarasa-Mono-SC-Nerd#17]
(set-face-attribute 'width-font-face nil :font "Sarasa Mono SC Nerd")
目前我是这么设置的

**Comment by laishulu** [comment]
:font

When specifying this attribute using set-face-attribute or set-face-font (see [Face Attribute Functions], you may also supply a font spec, a font entity, or a string. Emacs converts such values to an appropriate font object, and stores that font object as the actual attribute value. If you specify a string, the contents of the string should be a font name (see [Fonts](https://www.gnu.org/software/emacs/manual/html_node/emacs/Fonts.html#Fonts) in The GNU Emacs Manual); if the font name is an XLFD containing wildcards, Emacs chooses the first font matching those wildcards. Specifying this attribute also changes the values of the :family, :foundry, :width, :height, :weight, and :slant attributes.
