### ISSUE TITLE
Win11无法设置为PowerShell字体

### ISSUE THREAD

**Issue by Waterkin** [laishulu/Sarasa-Mono-SC-Nerd#18]
下载所有ttf文件并导入系统字体后：
![image](https://user-images.githubusercontent.com/41324537/173876151-09e933ac-e5f7-485e-ab48-80ee8528df5c.png)

**Comment by fang2hou** [comment]
应该是终端设定中字体相关的缓存没有刷新, 重启一下你的 Terminal 软件即可.

**Comment by Waterkin** [comment]
> 应该是终端设定中字体相关的缓存没有刷新, 重启一下你的 Terminal 软件即可.
谢谢，已经解决了！
