### ISSUE TITLE
Nerd字符只占一个半角字符宽度，但显示为两个字符宽度

### ISSUE THREAD

**Issue by CarterLi** [laishulu/Sarasa-Mono-SC-Nerd#19]
Sarasa-Mono-SC-Nerd:
<img width="970" alt="image" src="https://user-images.githubusercontent.com/6134068/187414027-6fa59a91-ad96-4e79-ae43-90db5223bb1d.png">

Iosevka Nerd Font Mono:
<img width="970" alt="image" src="https://user-images.githubusercontent.com/6134068/187414159-c93088d8-0f51-42ec-9e6e-b7f7abd28373.png">

**Comment by laishulu** [comment]
原因可能找到了，这几天我把新版弄出来试试。

**Comment by laishulu** [comment]
Iosevka这种英文字体打nerd补丁的话，如果指定是mono字体，所有的图标都是一个英文字符宽度，以保持对齐。
中文字体没法直接这么做，会造成每个中文字也占一个英文字符宽度，字之间会重叠。

我刚才发布了最新版的字体，通过修改补丁程序让中文字体也能用上一个英文字符宽度的图标。

新版包括两种字体：Sarasa Mono SC Nerd 和 Sarasa Mono SC Wide Nerd，各包含十种 样式（Regular, Bold, Italic 等等）。两个字体的唯一区别是：Nerd Fonts图标在前 者占一个英文字宽，在后者占一个中文字宽。

**Comment by CarterLi** [comment]
经测试，已经完美解决
