### ISSUE TITLE
中文的引号，好像只有一个字节宽度？导致如果有双引号的中文就对不齐啦

### ISSUE THREAD

**Issue by haoisli9** [laishulu/Sarasa-Mono-SC-Nerd#2]
中文的引号，好像只有一个字节宽度？导致如果有双引号的中文就对不齐啦

**Comment by laishulu** [comment]
>中文的引号，好像只有一个字节宽度？

是的。好奇怪，竟然不是全角的。
我看看是怎么回事。

**Comment by laishulu** [comment]
https://zh.wikipedia.org/zh/%E5%BC%95%E5%8F%B7

这个引号，本身英文里面就有，
所以，在等宽字体中，肯定是半角了。
<img width="491" alt="图片" src="https://user-images.githubusercontent.com/1224321/89561386-00747380-d84b-11ea-9d98-c902720da434.png">
