### ISSUE TITLE
Vscode 无法识别 Sarasa Mono SC Wide Nerd

### ISSUE THREAD

**Issue by idlesilver** [laishulu/Sarasa-Mono-SC-Nerd#2]
Vscode 无法识别 Sarasa Mono SC Wide Nerd，但是可以识别Sarasa Mono SC Nerd。
在windows terminal的外观设置下拉列表中也只能找到Sarasa Mono SC Nerd，没有wide版本。
win11系统设置中可以看到两种字体都安装了，在word，ppt中能正常使用。

win11 22H2

**Comment by laishulu** [comment]
我在windows虚拟机里测试了一下，确实有这个问题。
抽空看看问题出在哪里。

**Comment by laishulu** [comment]
<img width="385" alt="Snipaste_2023-02-25_22-08-17" src="https://user-images.githubusercontent.com/1224321/221361390-13419cb9-3da4-4175-a069-3c1a9d8f4e95.png">

wide nerd 字体在系统字体里显示成nerd字体。
我看看问题出在哪里。
macos里面没这个问题。

**Comment by laishulu** [comment]
找到原因了。字体名中带wide就会引起这个问题。
在字体工具里，还会多出来“半展开”这几个字。
我把`wide nerd`改成 `widenerd`就行了。
等我这两天提交新版本吧。

**Comment by laishulu** [comment]
见：https://github.com/be5invis/Sarasa-Gothic/issues/317
`wide nerd` 存在和mono同样的问题。

因此本项目将基于Term重新制作，项目名称也将做相应的更改。
并且，将不再提供wide nerd字体。
https://github.com/laishulu/Sarasa-Mono-SC-Nerd/issues/3#issuecomment-1445260450

**Comment by laishulu** [comment]
新版已发布
