### ISSUE TITLE
nf-mdi-sleep 这个字符好像和中文的“鈴”冲突

### ISSUE THREAD

**Issue by luozhiya** [laishulu/Sarasa-Mono-SC-Nerd#20]
nf-mdi-sleep
f9b1

鈴

**Comment by laishulu** [comment]
<img width="82" alt="Snipaste_2023-02-12_01-09-44" src="https://user-images.githubusercontent.com/1224321/218271288-7793ebf0-1ada-4c05-b42d-e2647ecbc425.png">
没问题啊。我从这个issue的标题上复制粘贴的。

**Comment by luozhiya** [comment]
要复制nf-mdi-sleep那个图标，不是复制鈴

**Comment by laishulu** [comment]
https://notes.taylantatli.com/cheatsheets/nerd-fonts/

<img width="340" alt="Snipaste_2023-02-14_22-30-25" src="https://user-images.githubusercontent.com/1224321/218770206-daf84a32-8440-4236-bb5b-788bbfa4584e.png">
nf-mdi-sleep占用的是`鈴`这个值。

为避免冲突，本字体在将nerd fonts图标合并到Sarasa是，
只要发现原始Sarasa字体中有的字，就跳过去，
而不用nerd fonts的图标替代原有的字符。
