### ISSUE TITLE
字符位置偏上

### ISSUE THREAD

**Issue by so1ar** [laishulu/Sarasa-Mono-SC-Nerd#21]
![1666943466_grim](https://user-images.githubusercontent.com/54471528/198534384-e8b55f42-41e3-42ac-9dfa-56da06e7e9f0.png)
比如在浏览器标签中，字符与图标没有对齐

**Comment by laishulu** [comment]
左边那个不是字体，
是图片：favicon.ico,
见 https://zh.wikipedia.org/zh-cn/Favicon

**Comment by so1ar** [comment]
> 左边那个不是字体， 是图片：favicon.ico, 见 https://zh.wikipedia.org/zh-cn/Favicon

我的意思就是说，字符与左边的 favicon 没有对齐，略微偏上。

**Comment by laishulu** [comment]
见下图：
<img width="394" alt="Snipaste_2022-10-29_11-21-31" src="https://user-images.githubusercontent.com/1224321/198802579-ace9470b-36f0-40f0-b2bc-c936f4ab8692.png">

第一个是我的firefox上macos自带的默认字体。
第二个是你的截屏
第三个是Sarasa Nerd字体。

从Y开口来看，你的截屏是系统默认字体，
不是Sarasa Nerd，
而且我patch的时候，没有对原始Sarasa做过任何改动

我看了下我这边，仅就youtube而言，
firefox中字体和图标底部对齐
而chrome中字体和图标顶部对齐。
而大多数网站，两个浏览器字体相对图标都是居中的

**Comment by so1ar** [comment]
那可能是我的字体设置的问题了，我使用的是 Archlinux，在修改字体之前字符和图标是可以对齐的。删除了多余的字体，GTK 和 QT 都设置了默认字体是 Sarasa Nerd，Firefox 设置里面也设置了字体使用 Sarasa Nerd，但是在一些界面还是会使用其他的字体，很奇怪，应该不是Sarasa Nerd 的问题，我再研究研究。
