### ISSUE TITLE
在VSCode编辑器内英文字体字宽不对

### ISSUE THREAD

**Issue by NeoFantom** [laishulu/Sarasa-Mono-SC-Nerd#22]
如题。在 VSCode 中设置 `"editor.fontFamily": "Sarasa Mono SC Nerd",` 后，中文以 sarasa 字体显示，然而英文似乎 fallback 回了某个默认字体，于是中英字体不再是二倍的关系了。请问如何解决？

![image](https://user-images.githubusercontent.com/38828722/212265288-6fe8a1f9-6498-4310-bfa4-00e8905d0ccc.png)

**Comment by laishulu** [comment]
你可能需要重启一下vscode？
你这个中英文都不是Sara mono sc字体。
是雅黑吧？
