### ISSUE TITLE
这个字体比较老了，很多新的符号都不包含。（已解决）

### ISSUE THREAD

**Issue by xiehuc** [laishulu/Sarasa-Mono-SC-Nerd#23]
https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/issues/17

可以使用上面的脚本，直接对上游 nerd font 修复就行了。不需要重新打nerd font，方便快捷

**Comment by laishulu** [comment]
没明白你的意思。
你是说sarasa字体比较老，还是nerd font版本比较老？
脚本的输入是什么？

**Comment by laishulu** [comment]
读了下你给的项目链接，很棒！

**Comment by xiehuc** [comment]
en nerdfont比较老了，jonz94的和上游保持同步，会定期把新的nerdfont打进去。

**Comment by laishulu** [comment]
已更新到最新版。
包含两个字体：Sarasa Mono SC Nerd 和 Sarasa Mono SC Wide Nerd，各包含十种 样式（Regular, Bold, Italic 等等）。两个字体的唯一区别是：Nerd Fonts图标在前者占一个英文字宽，在后者占一个中文字宽。

我看你是采用微调ascend值的方式来解决powerline的对齐问题。
这种方式，你字体放到很大的话，还是对齐的么？
我试了一下，可能需要进一步微调才可以得到满意的结果。

我这里的一直采用的方案是垂直缩放相关图标到最大，效果满意。
