### ISSUE TITLE
4.0.0版本，macos下不识别等宽

### ISSUE THREAD

**Issue by oceanyeo** [laishulu/Sarasa-Mono-SC-Nerd#3]

**Comment by oceanyeo** [comment]
在终端的效果
<img width="416" alt="bug" src="https://user-images.githubusercontent.com/4575740/221099601-3235df6f-fb17-43b0-9d83-b3f16ba32b11.png">

**Comment by oceanyeo** [comment]
字体册
<img width="400" alt="截屏2023-02-24 下午1 30 47" src="https://user-images.githubusercontent.com/4575740/221099833-10de4d18-ecb2-4402-9a2f-0c8dd6410046.png">

**Comment by laishulu** [comment]
> 字体册 <img alt="截屏2023-02-24 下午1 30 47" width="400" src="https://user-images.githubusercontent.com/4575740/221099833-10de4d18-ecb2-4402-9a2f-0c8dd6410046.png">

 That doesn't necessarily contain all the monospace fonts. It's just a predefined collection added by Apple.

**Comment by laishulu** [comment]
> 在终端的效果 <img alt="bug" width="416" src="https://user-images.githubusercontent.com/4575740/221099601-3235df6f-fb17-43b0-9d83-b3f16ba32b11.png">

我这边也复现了。
有空研究一下。

**Comment by laishulu** [comment]
> > 字体册 <img alt="截屏2023-02-24 下午1 30 47" width="400" src="https://user-images.githubusercontent.com/4575740/221099833-10de4d18-ecb2-4402-9a2f-0c8dd6410046.png">
> 
> 原始的`等距更纱黑体SC `在里面。 可能是OS/2表里的PANOSE信息在patch中丢失了。 我研究一下。

这块搞定了。
等我看看✅和❎的问题能不能搞定，搞定的话我发个新版出来

**Comment by laishulu** [comment]
这是原始`等距更纱黑体`的问题。

**Comment by laishulu** [comment]
https://github.com/be5invis/Sarasa-Gothic/issues/317

**Comment by laishulu** [comment]
Sarasa官方建议用Term字体。见：https://github.com/be5invis/Sarasa-Gothic/issues/317

因此本项目将基于Term重新制作，项目名称也将做相应的更改。

**Comment by laishulu** [comment]
新版已发布
