### ISSUE TITLE
在win10 vscode中连字符不能正确显示

### ISSUE THREAD

**Issue by owtotwo** [laishulu/Sarasa-Mono-SC-Nerd#5]
环境：
 - Win10 Pro 1909 x64 (18363.1082)
 - Vscode v1.50.0
 - Sarasa-Mono-SC-Nerd-2.0.1

图例：
![LigaturesError](https://user-images.githubusercontent.com/13444035/95744820-8e932d00-0cc6-11eb-8a79-fd97f4bd61f5.png)

但在Windows Terminal中能正确显示：
![LigaturesOk](https://user-images.githubusercontent.com/13444035/95744881-af5b8280-0cc6-11eb-8b2d-2c6e9ec45cad.png)

其他的字体如`FiraCode NF`能在Vscode中正确显示连字符：
![LigaturesOkInOtherFonts](https://user-images.githubusercontent.com/13444035/95745236-46c0d580-0cc7-11eb-9eee-8cfee8fdf99e.png)

我不知道是我哪里出错了 T_T

**Comment by laishulu** [comment]
有一点奇怪啊，
为啥`"`里面，你又加了`'`呢？
不过应该跟本issue无关

这个基础字体里面，
sarasa mono sc，本身是带ligature的
然后nerd font在patch的时候，
可能就有不同的处理。

我基于`sarasa fixed sc`做个看看，
这个本身就没有ligature，
所以nerd font的处理应该就和Fira code一样了

**Comment by owtotwo** [comment]
`"`里面加了`'`是因为`fontFamily`是支持多个字体的，如：`{ "editor.fontFamily": "'FiraCode NF', Consolas, 'Courier New', monospace" }`，这个应该不影响，我只是为了演示把其他几个字体删了而已，加上了情况也是一致的。

`等距更纱黑体 SC`确实有ligatures，但`Fira Code`本身好像也有ligatures，[Nerd-Fonts](https://github.com/ryanoasis/nerd-fonts)提供的patched `Fira Code`，也就是`FiraCode NF`似乎在vscode上是正常的（图三），会不会跟字体本身有没有ligatures关系不大呢？

不知道会不会是打patch的时候什么东西冲突了，只是我电脑环境不太能跑[Nerd-Fonts](https://github.com/ryanoasis/nerd-fonts)的Patch，也只能瞎猜测了。 😥

**Comment by bickman** [comment]
是的，sarasa fixed 刚好没有连字的，要连字需要ligature，就是用 sarasa mono 或者 sarasa term, 写代码一般mono用的多一些吧

**Comment by LucasIcarus** [comment]
`sarasa mono sc NF` 在 Mac VSCode 上测试 `ligature` 可以正常生效 

只是有些连字符的处理比如 `===` 处理的和 Fira Code 不一致

**Comment by onsummer** [comment]
用的最新的发布字体，才意识到这个是没有连字符的，希望大佬能把 `Sarasa Term SC` 或 `Fira Code Retina` 的连字符弄进来（个人觉得 `Fira Code Retina` 的连字符比 `Sarasa Term SC` 的好看一些），谢谢，新年快乐~~

![image](https://user-images.githubusercontent.com/26168955/107074840-40310d80-6824-11eb-97ce-26eac57dbeb4.png)

**Comment by laishulu** [comment]
nerd font的代码里，在某些情况下，会将长度超过2个英文字符宽度的字符丢弃，不打包到字体里。
