### ISSUE TITLE
本项目字体在Windows GVim上表现不正常，原版更纱表现正常

### ISSUE THREAD

**Issue by dodowhat** [laishulu/Sarasa-Mono-SC-Nerd#6]
环境：
- Windwos 10 Pro 20H2
- GVim version 8.1.1
- Sarasa-Mono-SC-Nerd-2.0.1

截图：
![nerd](https://user-images.githubusercontent.com/44317355/101980428-2d74df00-3ca0-11eb-8667-ba42a80f2a67.png)

对比原版更纱截图：
![origin](https://user-images.githubusercontent.com/44317355/101980438-41204580-3ca0-11eb-90b3-b712a431d4be.png)

**Comment by laishulu** [comment]
正文OK么？
我这里启动界面和正文都OK

<img width="1121" alt="图片" src="https://user-images.githubusercontent.com/1224321/101980896-bccfc180-3ca3-11eb-81b9-0ec7088e865e.png">


<img width="373" alt="图片" src="https://user-images.githubusercontent.com/1224321/101980857-70848180-3ca3-11eb-804e-1e817121c764.png">

我是测试的gvim 8.2.

你那边是不是还有别的设置？
本项目并没有改动原始的sarasa字体。

**Comment by laishulu** [comment]
我注意到，你的gvim是英文启动界面，我的gvim是中文启动界面。

本项目在对原始的sarasa字体文件进行patch时，
对字体在Chinese (PRC)和English (US)下的Family, SubFamily和 UniqueID等多个属性进行了设置

可能与那个有关。

**Comment by dodowhat** [comment]
正文也是一样的表现，不OK。确实我的系统语言是英文。

**Comment by laishulu** [comment]
https://github.com/laishulu/Sarasa-Mono-SC-Nerd/pull/12
