### ISSUE TITLE
在 Jetbrains 系列中显示异常，中文字符为4个英文字符长度

### ISSUE THREAD

**Issue by seyoatda** [laishulu/Sarasa-Mono-SC-Nerd#8]
![image](https://user-images.githubusercontent.com/24985838/127446422-de97a597-406d-45c4-b0e7-1ddd01b68052.png)
不是空格。
![image](https://user-images.githubusercontent.com/24985838/127446748-4f55dec0-9726-4c92-aba4-7c8ca3ca6cc4.png)

**Comment by cwt9562** [comment]
+1

**Comment by addv** [comment]
该字体在EmEditor中也存在同样问题。

**Comment by Howlaind** [comment]
似乎和 #7 描述的是同一件事。
可能是 FontForge 和 Sarasa 字体本来就有的兼容性问题？
用 FontForge 读入 Sarasa 字体后，不做任何修改，直接导出后的字体也能复现。

操作环境

> macOS Catalina 10.15.7
> fontforge 20201107
> sarasa-gothic-ttf-unhinted-0.35.0

执行如下命令，读入Sarasa字体后直接导出：
`fontforge -c 'open("sarasa-mono-sc-regular.ttf").generate("converted_sarasa-mono-sc-regular.ttf")'`

会有以下报错：
`Attempt to output -48076 into a 16-bit field. It will be truncated and the file may not be useful.`

macOS下倒是没能看出什么不对。
Windows下直接预览字体就能看到中文间距异常。

**Comment by laishulu** [comment]
这个线索很有价值，
也许可以搜到别人是怎么解决的。

我自己搞不定那么深入的问题。

**Comment by laishulu** [comment]
有线索了。
http://www.albertzhou.net/blog/2021/08/emacs-line-height.html
<img width="726" alt="Snipaste_2021-11-21_23-02-18" src="https://user-images.githubusercontent.com/1224321/142767334-22b0557a-116c-4cd3-a966-8651e954ef64.png">
<img width="767" alt="Snipaste_2021-11-21_23-00-40" src="https://user-images.githubusercontent.com/1224321/142767342-8c040f6f-f65b-4f95-81a2-a8f0e9aa4737.png">

**Comment by Howlaind** [comment]
貌似问题并不与这个 Win Ascent / Win Descent 字段相关。我修改它也没有产生预计的效果。

不过我根据您找到的那篇博客，用 ttx 比较了 FontForge 生成的字体与更纱字体 OS/2 表的区别。
发现只要将 xAvgCharWidth 字段设置成更纱字体原本的500，就能解决问题。

从微软的 [文档](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#xavgcharwidth) 来看，这确实是一个记录字体宽度的字段。

我还寻找过用 FontForge 来修改这个字段的方法。但通过这个 [issues](https://github.com/fontforge/fontforge/issues/1410#issuecomment-164286513) 得知，我们无法通过 FontForge 手动修改这个字段。

我还找到一篇 [博客文章](https://itouhiro.hatenablog.com/entry/20140910/font)（日语），里面提到了一个用 FontForge 修复东亚文字过宽的脚本。是将tff格式字体导出成sfd格式，直接修改sfd的裸数据后，再强制转换成tff格式的。挺繁琐。并且博客中也提到其适用的字体很少，还是推荐了使用 txx 来修改 xAvgCharWidth 字段。我就也没试过。

所以，要不然我们这就还是在转换完成之后，用 txx 处理一下好了。

**Comment by laishulu** [comment]
fontforge不支持修改这个字段。
https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.font.os2_codepages

因为这个字段只在老版本的os/2 表中有效，
https://docs.microsoft.com/en-us/typography/opentype/spec/os2#os2-field-details

所以，还是用txx来修改最方便了。

**Comment by laishulu** [comment]
https://pypi.org/project/fonttools/

这个里面自带ttx，那肯定没问题了。
会很方便

**Comment by laishulu** [comment]
https://titanwolf.org/Network/Articles/Article?AID=4fc8c131-59be-40a2-9b19-9a86b6b2b3c1
